/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as ConfigRouteImport } from './../pages/config'
import { Route as HomeRouteImport } from './../pages/home'
import { Route as ReportRouteImport } from './../pages/report'

const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/config': typeof ConfigRoute
  '/home': typeof HomeRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesByTo {
  '/config': typeof ConfigRoute
  '/home': typeof HomeRoute
  '/report': typeof ReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/config': typeof ConfigRoute
  '/home': typeof HomeRoute
  '/report': typeof ReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/config' | '/home' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/config' | '/home' | '/report'
  id: '__root__' | '/config' | '/home' | '/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConfigRoute: typeof ConfigRoute
  HomeRoute: typeof HomeRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConfigRoute: ConfigRoute,
  HomeRoute: HomeRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
